#!/bin/bash

#Copyright © 2016 Damian Majchrzak (DamiaX)
#https://github.com/DamiaX/D-Vshare.io/

version="0.2";
app_name="D-Vshare.io video downloader";
temp_files=(.temp.dvs .out.dvs .title.dvs);
connect_test_url=(google.com facebook.com kernel.org);
version_url="https://raw.githubusercontent.com/DamiaX/D-Vshare.io/master/VERSION";
up="https://raw.githubusercontent.com/DamiaX/D-Vshare.io/master/Core/up.sh";
video_dir="$HOME/vshare.io_movies";
arg1="$1";
arg2="$2";
arg3="$3"

term="/dev/tty";

default_answer()
{
if [ -z $answer ]; then
answer='y';
fi
}

check_data()
{
if [[ ! -d $video_dir ]] ;
then
mkdir $video_dir;
fi
}

update()
{
wget --no-cache --no-dns-cache -q $version_url -O ${temp_files[0]}
echo "$version" > ${temp_files[1]}

cat ${temp_files[0]}|tr . , >${temp_files[2]}
cat ${temp_files[1]}|tr . , >${temp_files[0]}

sed -i 's@,@@g' ${temp_files[0]}
sed -i 's@,@@g' ${temp_files[2]}

ver7=`cat "${temp_files[0]}"`
ver9=`cat "${temp_files[2]}"`

if [ $ver7 -eq $ver9 ]
    then
show_text 35 "=> Checking the version $app_name..."
else
show_text 37 "=> Download a newer version of $app_name..."

wget -q $up -O ${temp_files[3]}

chmod +x "${temp_files[3]}"

./"${temp_files[3]}" $0
exit;
fi
}

clear_data()
{
rm -rf "${temp_files[*]}";
}

test_connect()
{
ping -q -c1 ${connect_test_url[0]} > "${temp_files[0]}";
if [ "$?" -eq "2" ];
then
ping -q -c1 ${connect_test_url[1]} > "${temp_files[0]}";
if [ "$?" -eq "2" ];
then
ping -q -c1 ${connect_test_url[2]} > "${temp_files[0]}";
if [ "$?" -eq "2" ];
then
if [ "$1" = "0" ]
then
show_text 31 "No connection to the Internet. \nAborting.";
rm -rf "${temp_files[0]}";
exit;
else
rm -rf "${temp_files[0]}";
exit;
fi
fi
fi
fi
}

show_text()
{
	echo -e -n "\E[$1;1m$2\033[0m"
 	echo ""
}

parse()
{
sed -i 's@<a style="text-decoration:none;" href="@ <program>@g' ${temp_files[0]};
sed -i 's@">Click here</a> to download requested file.@ </program>@g' ${temp_files[0]};
grep "<program>" ${temp_files[0]} > ${temp_files[1]};
awk -vRS="</program>" '{gsub(/.*<program.*>/,"");print}' ${temp_files[1]} > ${temp_files[0]};
grep "http*" ${temp_files[0]} > ${temp_files[1]};
}

download_dir()
{
if [ -z "$arg3" ];
then
wget $link -O "$video_dir/$file_name_d";
else
wget $link -O "$arg3/$file_name_d";
fi
}

download_file()
{
link=`cat ${temp_files[1]};`;
roz=`echo $link | awk 'BEGIN { FS = "." }; {print $4}'`;

if [ -z "$arg2" ]; 
then
file_name_d="$RANDOM.$roz";
else
file_name_d="$arg2.$roz";
fi

if [ -z "$arg1" ]; 
then
show_text 31 "Start download? [Y/n]";
read answer < $term;
default_answer;

if [[ $answer == "T" || $answer == "t" || $answer == "y" || $answer == "Y" ]]; 
then
download_dir;
fi

else
download_dir;
fi
}

check_arg()
{
if [ -z "$arg1" ]; 
then
show_text 33 "Enter address video to download..."
read video_adress <$term
wget -q $video_adress -O ${temp_files[0]};
else
wget -q $arg1 -O ${temp_files[0]};

fi
}


hello()
{
clear;
clear_data;
show_text 33 "$app_name [$version]";
test_connect;
update;
check_data;
}

main()
{
hello;
check_arg;
parse;
download_file;
clear_data;
show_text 34 "Autor: Damian Majchrzak (DamiaX).";
}

main;
