#!/bin/bash

version="0.2"
temp_files=(.temp.dvs .out.dvs .title.dvs);
connect_test_url=(google.com facebook.com kernel.org);
video_dir="$HOME/vshare.io_movies"
arg1="$1";
arg2="$2";
arg3="$3"

term="/dev/tty";

default_answer()
{
if [ -z $answer ]; then
answer='y';
fi
}

check_data()
{
if [[ ! -d $video_dir ]] ;
then
mkdir $video_dir;
fi
}

test_connect()
{
ping -q -c1 ${connect_test_url[0]} > "${temp_files[0]}";
if [ "$?" -eq "2" ];
then
ping -q -c1 ${connect_test_url[1]} > "${temp_files[0]}";
if [ "$?" -eq "2" ];
then
ping -q -c1 ${connect_test_url[2]} > "${temp_files[0]}";
if [ "$?" -eq "2" ];
then
if [ "$1" = "0" ]
then
show_text 31 "$no_connect";
rm -rf "${temp_files[0]}";
exit;
else
rm -rf "${temp_files[0]}";
exit;
fi
fi
fi
fi
}

show_text()
{
	echo -e -n "\E[$1;1m$2\033[0m"
 	echo ""
}

parse()
{
sed -i 's@<a style="text-decoration:none;" href="@ <program>@g' ${temp_files[0]};
sed -i 's@">Click here</a> to download requested file.@ </program>@g' ${temp_files[0]};
grep "<program>" ${temp_files[0]} > ${temp_files[1]};
awk -vRS="</program>" '{gsub(/.*<program.*>/,"");print}' ${temp_files[1]} > ${temp_files[0]};
grep "http*" ${temp_files[0]} > ${temp_files[1]};
}

download_dir()
{
if [ -z "$arg3" ];
then
wget $link -O "$video_dir/$file_name_d";
else
wget $link -O "$arg3/$file_name_d";
fi
}

download_file()
{
link=`cat ${temp_files[1]};`;
roz=`echo $link | awk 'BEGIN { FS = "." }; {print $4}'`;

if [ -z "$arg2" ]; 
then
file_name_d="$RANDOM.$roz";
else
file_name_d="$arg2.$roz";
fi

if [ -z "$arg1" ]; 
then
show_text 31 "Start download? [Y/n]";
read answer < $term;
default_answer;

if [[ $answer == "T" || $answer == "t" || $answer == "y" || $answer == "Y" ]]; 
then
download_dir;
fi

else
download_dir;
fi
}

check_arg()
{
if [ -z "$arg1" ]; 
then
show_text 33 "Video url..."
read video_adress <$term
wget -q $video_adress -O ${temp_files[0]};
else
wget -q $arg1 -O ${temp_files[0]};

fi
}

main()
{
clear;
show_text 35 "D-Vshare.io"
test_connect;
check_data;
check_arg;
parse;
download_file;
show_text 34 "Autor: Damian Majchrzak (DamiaX).";
}

main;
rm -rf ${temp_files[*]};
